---
before:
  hooks:
    - make submodules
builds:
  - id: darwin-amd64
    main: ./cmd/algorand-indexer
    binary: algorand-indexer
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - MACOSX_DEPLOYMENT_TARGET=10.7
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      pre:
        - /osxcross/target/bin/osxcross-macports install boost
        - make go-algorand
        - make idb/postgres/internal/schema/setup_postgres_sql.go
    ldflags: &ld-flags
      - -X github.com/algorand/indexer/version.Hash={{ .FullCommit }}
      - -X github.com/algorand/indexer/version.Dirty={{ .Env.VERSION_DIRTY }}
      - -X github.com/algorand/indexer/version.CompileTime={{ .CommitTimestamp }}
      - -X github.com/algorand/indexer/version.GitDecorateBase64={{ .Env.VERSION_GIT_BASE64 }}
      - -X github.com/algorand/indexer/version.ReleaseVersion={{ .Version }}
  - id: linux-armhf
    main: ./cmd/algorand-indexer
    binary: algorand-indexer
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
      - CGO_CFLAGS=--sysroot=/sysroot/linux/armhf
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/armhf
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
      - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    hooks:
      pre:
        - apt-get update && apt-get install libboost-math-dev
        - make go-algorand
        - make idb/postgres/internal/schema/setup_postgresql.go
    flags:
      - -mod=readonly
    ldflags: *ld-flags

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-develop"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
